/**
 * @brief Level 1
 * @author Sebastien Alaiwan
 */

/*
 * Copyright (C) 2016 - Sebastien Alaiwan
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 */

#include <cassert>
#include "base/geom.h"
#include "base/util.h"
#include "game/game.h"
#include "game/level_common.h"

static const char data_level1[82][128 + 1] =
{
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXX     YYYYYYYYYYYY         YYY                                                               YYYYYYYYYYYYYYYYY       XXXXXXX",
  "XXXXX     YYYYYYYYYYYY          YY                                                              XXXXXXXXXXXXXXXXXXX       ZZZ XX",
  "XXXXX         XXXX                                           YYYYY                              X                 X           XX",
  "XXXXX                                 YY          YYY     YYYYY                                                               XX",
  "XXXXX                                 YYYY      YYYYY        YY       YYYYYYYY                                             @  XX",
  "XXXXX                           YY       Y                   YY       YYYYYYYY          YYYYYYY                           ZZZ XX",
  "XXXXX          ?           YYYYYYY                                                      YYYYYYY X                 X      XXXXXXX",
  "XXXXX         XXXX         YYYYY                                                        YYYYYYY XXXXXXXXXXXXXXXXXXX      XXXXXXX",
  "XXXXX     YYYYYYYYYYYY     YYYYY      *         *                                 *     YYYYYYY  YYYYYYYYYYYYYYYYY       XXXXXXX",
  "XXXXX     YYYYYYYYYYYY     YYYYY                                       XXXXX            XXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX     XXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX     XXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX      XXX  X     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX           X     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   Z       X     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  XXX      X     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX           X     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXX                    XXXXXX       Z   X     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                       XXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXX    *   *   *   *   XXXXXX      XXX  X     XXXXXXXXXXXXXXXXXXX                                   XXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXX                    XXXXXX           X     XXXXXXXXXXXXXXXXXXX                                XXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXBBXBBBXBBBBXBBBXBBBBXXXXXX   Z       X     XXXXXXXXXXXXXXXXXXX              XXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXX      X                    XXXXXX  XXX      X     XXXXXXXXXXXXXXXXXXX              XXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXX                                            X     XXXXXXXXXXXXXXXXXXX                 XXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXX                                       XX   X  %  XXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXX               b                       XX   X YYY XXXXXXXXXXXXXXXXX     XX                           XXXXXXXX",
  "XXXXXXXXXXXXXX           BBBXBBBXBBBBXBBBXBBBBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX     XX                                XXX",
  "XXXXXXXXXXXXXX         X                      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXX                    XXX",
  "XXXXXXXXXXXXXX      XXXX                      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXXX          @  XXX",
  "XXXXX              XXXXXX     *    *     *    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ZZZ XXX",
  "XX                 XXXXXX                     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XX                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XX     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XX     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XX   XXXXXXXX                  XXXXXXXXXXXXXXXXXXXXXXXXX                XXXXXXXXXXXXXX           XXXXX          XXXXXXXXXXXXXXXX",
  "XXX                                                                     XXXXXXXXXXXXXX                                     XXXXX",
  "XXX                                                                     XXXXXXXXXXXXXXXXXXXX                               XXXXX",
  "XXXXX                                                  #                                  XX           XXXXXXXX            XXXXX",
  "XXXXXXXXXXXXX   X   X   XX     XXXX                  XXX        !                                XXXXXXXXXXXXXXXXXXX       XXXXX",
  "XXXXXX      C                 XXXXXX                XXXX       ZZZ                               XXXXXXXXXXXXXXXXXXX      XXXXXX",
  "XXXXXX      C    *      *    XXXXXXXXX  *          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX     XXXXX",
  "XXXXXX      C               XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXXX",
  "XXXXXX    XXX              XXXXXXXXXXXXXXXX   XXXXXXXXXXXX      $           XXXXXXXXXXXXXXXXXXXXXXXX               X       XXXXX",
  "XXXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX     XXXXXXXXXXX      Z                  XXXXXXXXXXXXXXXXX        *      X     XXXXXXX",
  "XXXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX           XXXXX    XXXXX                       XXXXXXXXXX               X       XXXXX",
  "XXXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  X                 XXXXXXXXXXXXXX                       XAAAAAAAAAAAAAAAX  X    XXXXX",
  "XXXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  X    a            XXXXXXXXXXXXXXXXXXXXX                                        XXXXX",
  "XXXXXX    XXXXXXXXX                 XXXXXX  X    Z       #                        A  XXXXX                              XXXXXXXX",
  "XXXXXX                                   C  XXXXXXXXXXXXXXXX                      A XXXXXXXXXXXXX                       XXXXXXXX",
  "XXXXXX                                   C  XXXXXXXXXXXXXXXXX                     A XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXX             XXXXXXXXXXXXXXX      C  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                                                                   XXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                                                                   XXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                                                  XXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX         XXXXXXXXXXXXXXXXXXX           XXXXXXX  XXXXX     XXXXX  XXXXXXXXX    XXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX           XXXXXXXXXXXXXXXXXX        XXXXXXXXXX  XXXXX     XXXXX  XXXXXXXX     XXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXX                       @                      C   XXXXXXXXXXXXXXX  XXXXX     XXXXX  XXXXXXXX     XXX",
  "XXXXXXXXXXXXXXXXXXXXXX                          XXZZZXX                   C   XXXXXXXXXXXXXXX  XXXXX     XXXXX  XXXXXXXX     XXX",
  "XXXXXXXXXXXXXX                                 XXXXXXXXX                  C   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXX",
  "XXXXXXXXXXX                 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX     XXX",
  "XXXXXXXXXXX            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                               XXXXXXXXXXXXXXXXXXX     XXX",
  "XXXXXXXXXXX     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                               XXXXXXXXXXXXXXXXXXX     XXX",
  "XXXXXXXXXXX     XXXXXXXXXXXXXX               XXXXXXXXX                                               XXXXXXXXXXXXXXXXXXXX    XXX",
  "XXXXXXXXXXX                                                                                                       XXXXXX     XXX",
  "XXXXXXXXXXX                                                                                                          XXX     XXX",
  "XXXXXXXXXXX                    XXXXXXXXXXXXX                  ^                XXXXX                                         XXX",
  "XXXXXXXXXXX     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX       XXXXX    XXXXX       X     XXXXX             XXXXXXXX            XXX",
  "XXXXXXXXXXX     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX            X        X         X       X      XXXXX    XXXXXXXXXXXX        XXX",
  "XXXXXXXXXXX            XXXXXXXXXXXXX     XXXXXXXXX            X        X         X       X        X      XXXXXXXXXXXXXXXX    XXX",
  "XXXXXXXXXXX                 C                    C                                                                           XXX",
  "XXXXXXXXXXXXXX              C                    C                                                                           XXX",
  "XXXXXXXXXXXXXXXXXXXXXXX  c  C        XXX         C                                                                           XXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXZZZXXXXXXXXXXXXXXXXXX @ XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXZZZXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
};

void loadLevel1(Matrix<int>& tiles, Vector2i& start, IGame* game)
{
  auto data = toMatrix(data_level1);
  loadLevel(data, tiles, start, game);
}

