#!/bin/bash

set -euo pipefail

MAKE="make -j`nproc`"

echo "----------------------------------------------------------------"
echo "Reformatting ..."
scripts/reformat.sh src

echo "----------------------------------------------------------------"
echo "Building asmjs version"

PKG_CONFIG_LIBDIR=/home/ace/source/emscripten/emsdk_portable/emscripten/master/system/lib/pkgconfig \
PATH=/home/ace/source/emscripten/emsdk_portable/emscripten/master:$PATH \
  BIN=bin/asmjs \
  CXX=emcc \
  CXXFLAGS="-g0 -DNDEBUG" \
  LDFLAGS="-Xlinker,-s -g0 --preload-file res" \
  $MAKE bin/asmjs/deeep.html

echo "----------------------------------------------------------------"
echo "Building native version"

BIN=bin/native \
  CXX=g++ \
  $MAKE

./bin/native/tests.exe

echo Success!
