#!/bin/bash
set -euo pipefail

readonly scriptDir=$(dirname $0)
source $scriptDir/gamename.sh

readonly tmpDir=/tmp/deliver-$$
trap "rm -rf $tmpDir" EXIT
mkdir -p $tmpDir

function main
{
  echo "Delivering [$NAME]"
  make clean
  ./check
  deliverBinaryVersion
}

function deliverBinaryVersion
{
  local N=$NAME

  echo "-------------------------------------"
  echo "Building binaries"

  # Windows binaries
  CXXFLAGS+=-O3 \
  BIN=$tmpDir/bin/w64 \
    ./scripts/w64-make -j`nproc` >/dev/null

  gccVersion=$(x86_64-w64-mingw32-g++ -dumpversion)

  mkdir $tmpDir/$N
  cp -a $tmpDir/bin/w64/rel/game.exe                                 $tmpDir/$N
  cp /usr/x86_64-w64-mingw32/lib/libwinpthread-1.dll                 $tmpDir/$N
  cp /usr/lib/gcc/x86_64-w64-mingw32/$gccVersion/libstdc++-6.dll     $tmpDir/$N
  cp /usr/lib/gcc/x86_64-w64-mingw32/$gccVersion/libgcc_s_seh-1.dll  $tmpDir/$N
  cp /opt/envs/win64/bin/SDL2.dll                                   $tmpDir/$N
  mv $tmpDir/$N/game.exe $tmpDir/$N/$N.exe

  # GNU/Linux binaries
  CXXFLAGS+=-O3 \
  BIN=$tmpDir/bin/gnu \
    make -j`nproc` >/dev/null

  cp -a $tmpDir/bin/gnu/rel/game.exe                               $tmpDir/$N/$N.x86_64

  # Resources
  cp -a res                                                        $tmpDir/$N

  # Strip executables
  strip -s $tmpDir/$N/*.{exe,dll,x86_64}

  # Compress executables
  upx $tmpDir/$N/*.{exe,x86_64}

  (
    cd $tmpDir
    zip -q $N.zip -r $N
  )

  cp $tmpDir/$N.zip /tmp/
  du -hs /tmp/$N.zip
}

main
